name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  actions: read
  deployments: write
  # https://github.com/semantic-release/npm
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write  # to enable use of OIDC for npm provenance

jobs:
  deployment:
    environment: npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Run CI
        run: npm run CI

      - uses: codfish/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          # preset: "angular"
          # https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular
          # https://github.com/angular/angular/blob/main/CONTRIBUTING.md#commit-message-footer
          # branches: ["main"]
          additional-packages: |
            [ '@semantic-release/git', '@semantic-release/changelog' ]
          plugins: |
            [
              ["@semantic-release/commit-analyzer", {
                "preset": "angular"
              }],
              [
                "@semantic-release/release-notes-generator",
                {
                  "preset": "conventionalcommits",
                  "presetConfig": {
                    "types": [
                      { type: 'feat', section: 'Features', hidden: false },
                      { type: 'fix', section: 'Bug Fixes', hidden: false },
                      { type: 'perf', section: 'Performance Improvements', hidden: false },
                      { type: 'revert', section: 'Reverts', hidden: false },
                      { type: 'docs', section: 'Other Updates', hidden: true },
                      { type: 'style', section: 'Other Updates', hidden: true },
                      { type: 'chore', section: 'Other Updates', hidden: true },
                      { type: 'refactor', section: 'Other Updates', hidden: false },
                      { type: 'test', section: 'Other Updates', hidden: false },
                      { type: 'build', section: 'Other Updates', hidden: false },
                      { type: 'ci', section: 'Other Updates', hidden: false }
                    ]
                  }
                }
              ],
              "@semantic-release/changelog",
              "@semantic-release/npm",
              "@semantic-release/github",
              ["@semantic-release/git", {
                "assets": [
                  "package.json",
                  "CHANGELOG.md"
                ],
                "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
              }]
            ]
