name: Updating API and other documentation

on:

  pull_request:
    branches-ignore:
      - main
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'api-extractor.json'
      - 'test/examples/**/gulpfile.ts'
      - 'test/examples/**/readme.md'
      - 'readme.md'
      - '.github/workflows/docs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

jobs:
  update-docs:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Update API documentation
        run: npm run update-readme-API

      - name: Update readme.md
        run: npm run update-readme

      - name: Commit documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update API description and examples [skip ci]"
          file_pattern: 'docs/*.md readme.md test/examples/**/readme.md'
