name: Preparing readme

on:

  pull_request:
    branches-ignore:
      - main
  push:
    paths:
      - 'test/examples/**/gulpfile.ts'
      - 'readme.md'
      - '.github/workflows/readme.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: write

jobs:
  prepare-readme:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Update readme.md
        run: npm run update-readme

      - name: Commit readme.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs(readme): update examples and API description [skip ci]"
          file_pattern: 'readme.md'
