name: Build and tests

on:

  pull_request:
    branches:
      - main
  push:
    paths:
      - 'src/**'
      - 'package.json'
      - 'tsconfig.json'
      - 'tsup.config.ts'
      - 'test/**'
      - 'vitest.config.ts'
      - 'eslint.config.mjs'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests

jobs:
  tests:

    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        node-version: ['20.x', '21.x', '22.x', 'latest']

    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          # cache doesn't work without package-lock.json, but it is platform specific
          # cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Linting
        run: npm run lint

      # - name: Check module exports
      #   run: npm run check-exports

      - name: Tests
        run: npm run test

      - name: Report Coverage
        # if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          file-coverage-mode: all
